### ISSUE TITLE
Integrate Nix LSP

### ISSUE THREAD

**Issue by Moshyfawn** [zed-extensions/nix#1]
As of [`v0.129.0`](https://zed.dev/releases/preview/0.129.0) the extensions API now supports LSP integration 🥳 There's a community issue zed-industries/extensions#395 requesting to add Nix LSP extension integration.

**Comment by hasit** [comment]
@Moshyfawn thanks for letting me know. I will work on it soon.

**Comment by WeetHet** [comment]
Which one are you looking at? I suggest nixd, as its the most feature complete of them all

**Comment by niklaskorz** [comment]
> Which one are you looking at? I suggest nixd, as its the most feature complete of them all

Similar to https://github.com/nix-community/vscode-nix-ide, it should be configurable. Nixd never really worked for me, so the first thing I do in vscode-nix is setting the server path to [nil](https://github.com/oxalica/nil).
