### ISSUE TITLE
Version missmatch between zed and repository

### ISSUE THREAD

**Issue by simon-bueler** [zed-extensions/nix#18]
Just a question, why is in Zed the version of the nix extension 0.1.0 and the latest version in the repository is 0.0.4 ?

**Comment by notpeter** [comment]
The version in the repository is 0.1.0

https://github.com/zed-extensions/nix/blob/f17bcfae1df66b71a19b31dc22d1ea5098de9514/extension.toml#L4

The version in the zed extension store is 0.1.0
<img width="340" alt="Screenshot 2024-11-18 at 9 50 35" src="https://github.com/user-attachments/assets/164f2522-d4e1-4067-b337-e0daea6ec439">

There are some recent changes in the repository which have not yet been released. But all it takes is a version bump here and then a PR to the [zed-industries/extensions](https://github.com/zed-industries/extensions) repo to publish the updated version.
