### ISSUE TITLE
Why `close = false`?

### ISSUE THREAD

**Issue by Liamolucko** [zed-extensions/nix#3]
Ever since switching from Zed's built-in Nix support to this extension, it's been bugging me that Zed no longer auto-completes the matching closing bracket when I type an opening bracket. It seems like this is because `languages/nix/config.toml` specifies `close = false` for all its brackets, when the built-in support used `close = true`; is there any reason why you did it this way?

Same for `newline = false`, I also think that that should be true.

**Comment by 21CSM** [comment]
This is fixed by: #6
