### ISSUE TITLE
Extension maintenance

### ISSUE THREAD

**Issue by maxdeviant** [zed-extensions/nix#5]
Hello there @hasit,

It looks like there hasn't been any activity on this repository for a little while. Are you still interested in maintaining this extension?

We recently had someone contribute language server support for Nix in https://github.com/zed-industries/extensions/pull/857, and they cited the lack of response on #1 as a reason for creating a new extension.

We'd prefer for there to be a single Nix extension rather than having multiple competing extensions.

We have the @zed-extensions organization as a place to coordinate extension development that is also administrable by the Zed team. We could move the Nix extension there and grant you maintainer permissions.

If that is acceptable to you, you can go ahead and transfer the repository to me (@maxdeviant) and I will transfer it into the @zed-extensions organization.

**Comment by hasit** [comment]
Hello @maxdeviant 

I'd be happy to transfer the repository to @zed-extensions organization. I see that the community is ready to give it more love :)

**Comment by emilazy** [comment]
Hi @maxdeviant, would it be possible to get other people merge rights as there are a few open PRs that seem to be stalled? Maybe @msanft would be interested, or I could also try to dedicate some time to it?
