### ISSUE TITLE
Request: `nil` and other alternative lsp server support

### ISSUE THREAD

**Issue by ozwaldorf** [zed-extensions/nix#9]
Would be nice to support using alternative lsp servers, like [nil](https://github.com/oxalica/nil).

**Comment by deng232** [comment]
nil seems like having more feature completed

**Comment by ozwaldorf** [comment]
> nil seems like having more feature completed

I especially like that it provides suggestions for builtins, along with their arguments

**Comment by ozwaldorf** [comment]
It seems trivial to implement support for a custom binary config, but I wasn't able to test my changes as zed on nix doesn't work with development extensions

**Comment by niklaskorz** [comment]
`nixd` is pretty much unusable when working on nixpkgs (very high memory and CPU usage), so I too would like to see `nil` support

**Comment by matubu** [comment]
> It seems trivial to implement support for a custom binary config, but I wasn't able to test my changes as zed on nix doesn't work with development extensions

I am on NixOS and to test development extensions. I run `nix-shell` inside the zed repo. And then launch zed from their either from source with `cargo run --release` or just `zed` and then I can install development extensions with the button

![](https://github.com/user-attachments/assets/faab67b8-d712-4445-bf0a-cb28d9e8f7f8)

**Comment by inclyc** [comment]
> `nixd` is pretty much unusable when working on nixpkgs (very high memory and CPU usage), so I too would like to see `nil` support

Would you like to help us improve? File a issue on [nix-community/nixd](https://github.com/nix-community/nixd/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=), report it as a bug!
